name: LaTeX Build

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up LaTeX and required packages
      uses: docker://blang/latex:ctanfull
      with:
        args: >
          bash -c "
          apt-get update && apt-get install -y fonts-<Gill Sans> && apt-get clean
          "

    - name: Compile LaTeX document
      run: |
        xelatex -interaction=nonstopmode -halt-on-error card.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: card-output
        path: card.pdf
