name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Install XeTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
          with:
            root_file: main.tex
            latexmk_use_xelatex: true
            extra_fonts: M1-Data-Science-CS-Class/GillSans/*.otf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: card.pdf
