name: Build LaTeX document

on:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install TeXLive and required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex
          sudo apt-get install -y texlive-fonts-recommended
          sudo apt-get install -y texlive-latex-extra

      - name: Compile LaTeX document
        run: |
          xelatex -interaction=nonstopmode -halt-on-error card.tex
          bibtex card   # If you need BibTeX
          xelatex -interaction=nonstopmode -halt-on-error card.tex
          xelatex -interaction=nonstopmode -halt-on-error card.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: card.pdf
